export const environment = {
  production: false,
  base_url: "http://localhost:3000/api/",
  player_service_url: "players/",
  achievment_service_url: "/achievments/",
  login_service_url: "login/",
  nav_home: "",
  nav_players: "players",
  nav_player: "player/",
  nav_profile: "profile",
  nav_register: "register",
  nav_login: "login",
  param_playerId: "playerId",
  token_bearer: "Bearer ",
  token: "token",
  text_welcome: "Welcome to MEAN Table Tennis Players",
  text_page_not_found: "Page not found",
  text_home: "Home",
  text_players: "Players",
  text_profile: "Profile",
  text_register: "Register",
  text_login: "Login",
  text_logout: "Logout",
  text_login_failed: "Username or password is wrong",
  text_username: "Username",
  text_password: "Password",
  text_name: "Name",
  text_country: "Country",
  text_contest: "Contest",
  text_medal: "Medal",
  text_player_detail: "Player Detail",
  text_achievments: "Achievment",
  text_edit: "Edit",
  text_update: "Update",
  text_cancel: "Cancel",
  text_add_achievment: "Add Achievment",
  text_delete_profile: "Delete my profile",
  text_next: "Next",
  text_prev: "Prev",
  text_gold: "Gold",
  text_silver: "Silver",
  text_bronze: "Bronze",
  text_olympic_2020: "Olympic 2020",
  text_olympic_2016: "Olympic 2016",
  text_olympic_2012: "Olympic 2012",
  text_olympic_2008: "Olympic 2008",
  text_olympic_2004: "Olympic 2004",
  text_select_medal: "Please select medal",
  text_select_contest: "Please select contest",
  default_page: 1,
  default_page_count: 5,
  query_offset: "offset=",
  query_count: "count=",
  query_name: "name=",
};